[app]
title = Repartidor
package.name = repartidorapp
package.domain = com.repartidorapp
source.dir = .
source.include_exts = py,png,jpg,jpeg,json,kv,txt,ini
version = 1.0.0
requirements = python3,kivy,requests,plyer,openssl,urllib3
orientation = portrait
android.permissions = INTERNET, CAMERA, ACCESS_FINE_LOCATION, WRITE_EXTERNAL_STORAGE
android.api = 34
android.minapi = 21
android.ndk = 25b
android.archs = arm64-v8a
android.release_artifact = apk
android.accept_sdk_license = True
android.keystore = ./release.jks
android.keyalias = repartidor
android.keypass = repartidor123
android.storepass = repartidor123
